consul-agent:
    image: consul-agent
    links:
        - consul-server:consul-server
        - haproxy:haproxy
    hostname: "docker-agent"
    volumes:
        - ./docker-consul/0.5/consul-agent/config:/config
        - ./docker-consul/0.5/consul-agent/entrypoint.sh:/entrypoint.sh
    command: /bin/sh /entrypoint.sh
    # command: tail -f /dev/null

consul-server:
    image: consul-server
    ports:
        - "8500:8500"
        - "8400:8400"
        - "8600:53/udp"
    hostname: "consul-server"
    volumes:
        - ./docker-consul/0.5/consul-server/config:/config
        - ./docker-consul/0.5/consul-server/entrypoint.sh:/entrypoint.sh
    command: /bin/sh /entrypoint.sh

haproxy:
    image: haproxy
    volumes:
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    # ports:
    #     - "80:80"
